apiVersion: v1
kind: Namespace
metadata:
  name: kind-security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-reader
  namespace: kind-security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-reader
  namespace: kind-security
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-reader
  namespace: kind-security
subjects:
  - kind: ServiceAccount
    name: demo-reader
    namespace: kind-security
roleRef:
  kind: Role
  name: demo-reader
  apiGroup: rbac.authorization.k8s.io
